export default {
  SET_SLIDER: 'SET_SLIDER',
  SET_HEADLINE: 'SET_HEADLINE',
  SET_ACTIVITIES: 'SET_ACTIVITIES',
  SET_SUPER_SALE: 'SET_SUPER_SALE',
  SET_SHOPS: 'SET_SHOPS',
  SET_SEARCH_VAL: 'SET_SEARCH_VAL',
  SET_LOAD:'SET_LOAD'
}
